### PR TITLE
Chore/optimize report

### PR DESCRIPTION
**Pull request by gauravlochab**
Refactored the wallet_info, staking_report, and report scripts to improve code modularity by extracting common functions into a shared utils module. 
Key changes include:
- Modularized shared functions such as balance handling, color coding, and status printing.
- Implemented consistent error handling and logging across all scripts.
- Enhanced threshold checks and warnings for Safe and Agent balances.

### CODE REVIEW

**Comment by 0xArdi** [comment]
Do you mind re-basing to my branch?

**Comment by gauravlochab** [comment]
> Do you mind re-basing to my branch? `fix/fund-ops`

still need to do that ?

**Comment by gauravlochab** [comment]
> Do you mind re-basing to my branch? `fix/fund-ops`

sure let me do that

**Comment by gauravlochab** [comment]
> > Do you mind re-basing to my branch? `fix/fund-ops`
> 
> sure let me do that

done, no conflicts!

**Pull request merged**
